using TarkovMapCompanion.Data;
using TarkovMapCompanion.Maps;
using Xunit;

namespace TarkovMapCompanion.Tests;

/// <summary>
/// Joining the names Tarkov uses to the maps this app draws.
/// </summary>
/// <remarks>
/// The table this pins is the thing most likely to rot on a Tarkov patch, and its failure mode is
/// silent: an unrecognized location id means the map simply does not switch, with nothing on screen
/// to say why. So it is checked against the shipped data rather than against itself.
/// </remarks>
public sealed class MapNameIdTests
{
    /// <summary>
    /// Every location id in the bundled data reaches a map that is actually rendered.
    /// </summary>
    /// <remarks>
    /// Fails the moment a data refresh introduces a location the table has not been told about,
    /// which is exactly when somebody needs to know.
    /// </remarks>
    [Fact]
    public void EveryUpstreamNameIdResolves()
    {
        var catalog = MapCatalog.LoadEmbedded();
        var snapshot = MapDataStore.EmbeddedSnapshot();

        Assert.NotNull(snapshot);

        var ids = snapshot.Maps.Values
            .Select(m => m.NameId)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .ToArray();

        // If this is zero the snapshot was regenerated by a build that did not model nameId, and
        // every other assertion here would pass vacuously.
        Assert.Equal(snapshot.Maps.Count, ids.Length);

        var unresolved = ids.Where(id => catalog.ResolveByNameId(id) is null).ToArray();

        Assert.True(
            unresolved.Length == 0,
            $"no map for location id(s): {string.Join(", ", unresolved)}");
    }

    /// <summary>
    /// Variants land on the map that ships, rather than on nothing.
    /// </summary>
    /// <remarks>
    /// tarkov.dev treats Night Factory, the two extra Ground Zeros and the dark Lab as separate
    /// maps; the app ships thirteen and draws the same geometry for each pair.
    /// </remarks>
    [Theory]
    [InlineData("factory4_day", "factory")]
    [InlineData("factory4_night", "factory")]
    [InlineData("Sandbox", "ground-zero")]
    [InlineData("Sandbox_high", "ground-zero")]
    [InlineData("Sandbox_start", "ground-zero")]
    [InlineData("laboratory", "the-lab")]
    [InlineData("laboratory_dark", "the-lab")]
    [InlineData("RezervBase", "reserve")]
    [InlineData("TarkovStreets", "streets-of-tarkov")]
    public void VariantsFoldOntoTheirBaseMap(string nameId, string expected) =>
        Assert.Equal(expected, MapCatalog.LoadEmbedded().ResolveByNameId(nameId)?.NormalizedName);

    /// <summary>Case varies between maps in the game's own output, so matching cannot be exact.</summary>
    [Theory]
    [InlineData("BIGMAP")]
    [InlineData("bigmap")]
    [InlineData("BigMap")]
    public void MatchingIgnoresCase(string nameId) =>
        Assert.Equal("customs", MapCatalog.LoadEmbedded().ResolveByNameId(nameId)?.NormalizedName);

    /// <summary>
    /// A token that already is a map's name needs no table entry.
    /// </summary>
    /// <remarks>
    /// This is what keeps the alias table down to the four genuine oddities: the scene line says
    /// "customs" and "shoreline" for those maps, which are their normalized names already.
    /// </remarks>
    [Theory]
    [InlineData("customs")]
    [InlineData("shoreline")]
    [InlineData("woods")]
    public void ANormalizedNameResolvesWithoutAnEntry(string token) =>
        Assert.Equal(token, MapCatalog.LoadEmbedded().ResolveByNameId(token)?.NormalizedName);

    /// <summary>
    /// An unknown name resolves to nothing, not to the first map in the list.
    /// </summary>
    /// <remarks>
    /// The difference matters: this path is driven by the game log, where falling back would switch
    /// the user's map to Customs every time BSG adds a location the build has not heard of.
    /// </remarks>
    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData(null)]
    [InlineData("SomeMapAddedNextPatch")]
    public void AnUnknownNameResolvesToNothing(string? token) =>
        Assert.Null(MapCatalog.LoadEmbedded().ResolveByNameId(token));

    /// <summary>The table and the data agree on which map each id belongs to.</summary>
    [Fact]
    public void TheTableAgreesWithTheData()
    {
        var snapshot = MapDataStore.EmbeddedSnapshot();
        Assert.NotNull(snapshot);

        var known = MapNameIds.KnownNameIds.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var upstream = snapshot.Maps.Values
            .Select(m => m.NameId!)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .ToArray();

        var missing = upstream.Where(id => !known.Contains(id)).ToArray();
        Assert.True(missing.Length == 0, $"location id(s) missing from the table: {string.Join(", ", missing)}");

        var stale = known.Where(id => !upstream.Contains(id, StringComparer.OrdinalIgnoreCase)).ToArray();
        Assert.True(stale.Length == 0, $"table names location id(s) upstream no longer has: {string.Join(", ", stale)}");
    }
}
